name: Language Detection Workflow

#on:
#  schedule:
#    - cron: '0 */12 * * *'  # Run every 12 hours

on:
  push:
    branches:
      - main

jobs:
  process-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the language detection script
      - name: Run language detection
        run: python ../scripts/detect_language.py

      # Step 5: Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "data.dev.backyard"
          git config --global user.email "datadevbackyard@gmail.com"
          git add output_data/*.csv
          git commit -m "Update processed CSV files with detected languages"
          git push origin main
